# Generated by Django 5.2.3 on 2025-07-04 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'db_table': 'ISBN',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Book Title')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Bool Price')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Book cover')),
                ('description', models.CharField(max_length=255, verbose_name='Book Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_book', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='books', to='bookstore.categories')),
                ('isbn', models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='bookstore.isbn')),
            ],
            options={
                'db_table': 'Books',
            },
        ),
    ]
