# Generated by Django 5.2.3 on 2025-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=255, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Book Title')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Bool Price')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Book cover')),
                ('description', models.CharField(max_length=255, verbose_name='Book Description')),
            ],
        ),
    ]
