# Generated by Django 5.2.3 on 2025-07-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='Books',
        ),
    ]
