# Generated by Django 5.2.3 on 2025-07-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_books_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='bookstore.categories'),
        ),
    ]
